# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 825dbf5f632e4a852805a64ebff9621ab112079ab52f64a5801828b63a7b422af714a8fd90ef0f1c99f6f0955fc47b7e4a01473ce2fd2ef79a823eb362522d80

test:
  secret_key_base: a8fe4631657accfe7cc9b0563ee3fd92de10c0e2ba4588c49d4f3fca8a899a18e01403c7c5aab9748b53db771cd96f437987cdc04ed8ddc95258f88a10cb0b9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
